[package]
name = "api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
rocket = { version = "0.5", features = ["json", "serde_json"] }
rocket_okapi = "0.9"
rust-embed = "8"
lazy_static = "1.5"
serde = { workspace = true }
schemars = "0.8"
sysinfo = "0.33"
lambda-web = { version = "0.2", features = ["rocket05"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
