[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
sqlx = { workspace = true }
jsonwebtoken = "9"
sha2 = "0.10"
hex = "0.4"
rand = "0.8"
